name: CI - BookingYa Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: bookingya
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d bookingya"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run application
        working-directory: bookingya_students
        run: |
          mvn clean spring-boot:run -e &
          sleep 60

      - name: Give Gradle permissions
        run: chmod +x UnitTestBookinYa/gradlew

      - name: Run TDD unit tests
        working-directory: UnitTestBookinYa
        run: |
          ./gradlew clean test